DROP DATABASE IF EXISTS projeto_bd;
CREATE DATABASE projeto_BD;
USE projeto_BD;

CREATE TABLE funcionario(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,nome VARCHAR(200) NOT NULL
,cpf CHAR(14) NOT NULL UNIQUE
,data_nascimento CHAR(10) NOT NULL
);

CREATE TABLE cliente(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,nome VARCHAR(200) NOT NULL
,cpf CHAR(11) NOT NULL UNIQUE
,data_nascimento CHAR(10) NOT NULL
);

CREATE TABLE produto(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,nome VARCHAR(200) NOT NULL
,codigo CHAR(50)
,preco DECIMAL(3,2) NOT NULL
);

CREATE TABLE caixa(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,descricao VARCHAR(200)
,data_abertura DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE rcebimento(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,tipo VARCHAR(200)
,total DECIMAL(3,2) NOT NULL
,desconto DECIMAL(3,2) NOT NULL
,valor_final DECIMAL(3,2) NOT NULL
,data_recebimento DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE pedido(
id INT NOT NULL PRIMARY KEY AUTO_INCREMENT
,numero_mesa INT NOT NULL AUTO_INCREMENT
,situacao CHAR(1) NOT NULL DEFAULT 'S'
,total DECIMAL(3,2) NOT NULL
);
